services:
  app:
    volumes:
      - "${VOLUMES_DIR}/images:/var/www/html/images"
      - "./app/html/LocalSettings.php:/var/www/html/LocalSettings.php"
    labels:
      - traefik.http.routers.${SERVICENAME}.middlewares=default@file
