services:
  app:
    image: ghcr.io/mind-hochschul-netzwerk/${SERVICENAME}
    restart: unless-stopped
    container_name: ${SERVICENAME}
    volumes:
      - "${VOLUMES_DIR}/images:/var/www/html/images"
    environment:
      - DOMAINNAME
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD
      - MYSQL_DATABASE=database
      - SMTP_HOST
      - SMTP_SECURE
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASSWORD
      - SECRET_KEY
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICENAME}.middlewares=forwardauth@file
    depends_on:
      - db
    networks:
      - traefik
      - default

  db:
    image: mariadb
    restart: unless-stopped
    container_name: ${SERVICENAME}-db
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD
    volumes:
      - "./docker/sql:/docker-entrypoint-initdb.d:ro"
      - "${VOLUMES_DIR}/mariadb:/var/lib/mysql"

  adminer:
    image: adminer
    container_name: ${SERVICENAME}-adminer
    labels:
      - traefik.enable=true
    depends_on:
      - db
    networks:
      - traefik
      - default

networks:
  traefik:
    name: traefik
    external: true
